'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2407
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2407.
'
Namespace WebReference
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ABRXMLSearchSoap", [Namespace]:="http://abr.business.gov.au/ABRXMLSearch/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Address)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Organisation)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Individual)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ResponseBody))>  _
    Public Class ABRXMLSearch
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://abr.business.gov.au/abrxmlsearch/abrxmlsearch.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abr.business.gov.au/ABRXMLSearch/ABRSearchByABN", RequestNamespace:="http://abr.business.gov.au/ABRXMLSearch/", ResponseNamespace:="http://abr.business.gov.au/ABRXMLSearch/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ABRSearchByABN(ByVal searchString As String, ByVal includeHistoricalDetails As String, ByVal authenticationGuid As String) As <System.Xml.Serialization.XmlElementAttribute("ABRPayloadSearchResults", IsNullable:=true)> Payload
            Dim results() As Object = Me.Invoke("ABRSearchByABN", New Object() {searchString, includeHistoricalDetails, authenticationGuid})
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        Public Function BeginABRSearchByABN(ByVal searchString As String, ByVal includeHistoricalDetails As String, ByVal authenticationGuid As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ABRSearchByABN", New Object() {searchString, includeHistoricalDetails, authenticationGuid}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndABRSearchByABN(ByVal asyncResult As System.IAsyncResult) As Payload
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abr.business.gov.au/ABRXMLSearch/ABRSearchByASIC", RequestNamespace:="http://abr.business.gov.au/ABRXMLSearch/", ResponseNamespace:="http://abr.business.gov.au/ABRXMLSearch/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ABRSearchByASIC(ByVal searchString As String, ByVal includeHistoricalDetails As String, ByVal authenticationGuid As String) As <System.Xml.Serialization.XmlElementAttribute("ABRPayloadSearchResults", IsNullable:=true)> Payload
            Dim results() As Object = Me.Invoke("ABRSearchByASIC", New Object() {searchString, includeHistoricalDetails, authenticationGuid})
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        Public Function BeginABRSearchByASIC(ByVal searchString As String, ByVal includeHistoricalDetails As String, ByVal authenticationGuid As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ABRSearchByASIC", New Object() {searchString, includeHistoricalDetails, authenticationGuid}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndABRSearchByASIC(ByVal asyncResult As System.IAsyncResult) As Payload
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abr.business.gov.au/ABRXMLSearch/ABRSearchByName", RequestNamespace:="http://abr.business.gov.au/ABRXMLSearch/", ResponseNamespace:="http://abr.business.gov.au/ABRXMLSearch/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ABRSearchByName(ByVal externalNameSearch As ExternalRequestNameSearch, ByVal authenticationGuid As String) As <System.Xml.Serialization.XmlElementAttribute("ABRPayloadSearchResults", IsNullable:=true)> Payload
            Dim results() As Object = Me.Invoke("ABRSearchByName", New Object() {externalNameSearch, authenticationGuid})
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        Public Function BeginABRSearchByName(ByVal externalNameSearch As ExternalRequestNameSearch, ByVal authenticationGuid As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ABRSearchByName", New Object() {externalNameSearch, authenticationGuid}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndABRSearchByName(ByVal asyncResult As System.IAsyncResult) As Payload
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abr.business.gov.au/ABRXMLSearch/ABRSearchByNameAdvanced", RequestNamespace:="http://abr.business.gov.au/ABRXMLSearch/", ResponseNamespace:="http://abr.business.gov.au/ABRXMLSearch/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ABRSearchByNameAdvanced(ByVal externalNameSearch As ExternalRequestNameSearchAdvanced, ByVal authenticationGuid As String) As <System.Xml.Serialization.XmlElementAttribute("ABRPayloadSearchResults", IsNullable:=true)> Payload
            Dim results() As Object = Me.Invoke("ABRSearchByNameAdvanced", New Object() {externalNameSearch, authenticationGuid})
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        Public Function BeginABRSearchByNameAdvanced(ByVal externalNameSearch As ExternalRequestNameSearchAdvanced, ByVal authenticationGuid As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ABRSearchByNameAdvanced", New Object() {externalNameSearch, authenticationGuid}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndABRSearchByNameAdvanced(ByVal asyncResult As System.IAsyncResult) As Payload
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abr.business.gov.au/ABRXMLSearch/ABRSearchByNameAdvanced2006", RequestNamespace:="http://abr.business.gov.au/ABRXMLSearch/", ResponseNamespace:="http://abr.business.gov.au/ABRXMLSearch/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ABRSearchByNameAdvanced2006(ByVal externalNameSearch As ExternalRequestNameSearchAdvanced2006, ByVal authenticationGuid As String) As <System.Xml.Serialization.XmlElementAttribute("ABRPayloadSearchResults", IsNullable:=true)> Payload
            Dim results() As Object = Me.Invoke("ABRSearchByNameAdvanced2006", New Object() {externalNameSearch, authenticationGuid})
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        Public Function BeginABRSearchByNameAdvanced2006(ByVal externalNameSearch As ExternalRequestNameSearchAdvanced2006, ByVal authenticationGuid As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ABRSearchByNameAdvanced2006", New Object() {externalNameSearch, authenticationGuid}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndABRSearchByNameAdvanced2006(ByVal asyncResult As System.IAsyncResult) As Payload
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abr.business.gov.au/ABRXMLSearch/ABRSearchByNameSimpleProtocol", RequestNamespace:="http://abr.business.gov.au/ABRXMLSearch/", ResponseNamespace:="http://abr.business.gov.au/ABRXMLSearch/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ABRSearchByNameSimpleProtocol(ByVal name As String, ByVal postcode As String, ByVal legalName As String, ByVal tradingName As String, ByVal NSW As String, ByVal SA As String, ByVal ACT As String, ByVal VIC As String, ByVal WA As String, ByVal NT As String, ByVal QLD As String, ByVal TAS As String, ByVal authenticationGuid As String) As <System.Xml.Serialization.XmlElementAttribute("ABRPayloadSearchResults", IsNullable:=true)> Payload
            Dim results() As Object = Me.Invoke("ABRSearchByNameSimpleProtocol", New Object() {name, postcode, legalName, tradingName, NSW, SA, ACT, VIC, WA, NT, QLD, TAS, authenticationGuid})
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        Public Function BeginABRSearchByNameSimpleProtocol(ByVal name As String, ByVal postcode As String, ByVal legalName As String, ByVal tradingName As String, ByVal NSW As String, ByVal SA As String, ByVal ACT As String, ByVal VIC As String, ByVal WA As String, ByVal NT As String, ByVal QLD As String, ByVal TAS As String, ByVal authenticationGuid As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ABRSearchByNameSimpleProtocol", New Object() {name, postcode, legalName, tradingName, NSW, SA, ACT, VIC, WA, NT, QLD, TAS, authenticationGuid}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndABRSearchByNameSimpleProtocol(ByVal asyncResult As System.IAsyncResult) As Payload
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abr.business.gov.au/ABRXMLSearch/ABRSearchByNameAdvancedSimpleProtocol", RequestNamespace:="http://abr.business.gov.au/ABRXMLSearch/", ResponseNamespace:="http://abr.business.gov.au/ABRXMLSearch/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ABRSearchByNameAdvancedSimpleProtocol(ByVal name As String, ByVal postcode As String, ByVal legalName As String, ByVal tradingName As String, ByVal NSW As String, ByVal SA As String, ByVal ACT As String, ByVal VIC As String, ByVal WA As String, ByVal NT As String, ByVal QLD As String, ByVal TAS As String, ByVal authenticationGuid As String, ByVal searchWidth As String, ByVal minimumScore As String) As <System.Xml.Serialization.XmlElementAttribute("ABRPayloadSearchResults", IsNullable:=true)> Payload
            Dim results() As Object = Me.Invoke("ABRSearchByNameAdvancedSimpleProtocol", New Object() {name, postcode, legalName, tradingName, NSW, SA, ACT, VIC, WA, NT, QLD, TAS, authenticationGuid, searchWidth, minimumScore})
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        Public Function BeginABRSearchByNameAdvancedSimpleProtocol( _
                    ByVal name As String,  _
                    ByVal postcode As String,  _
                    ByVal legalName As String,  _
                    ByVal tradingName As String,  _
                    ByVal NSW As String,  _
                    ByVal SA As String,  _
                    ByVal ACT As String,  _
                    ByVal VIC As String,  _
                    ByVal WA As String,  _
                    ByVal NT As String,  _
                    ByVal QLD As String,  _
                    ByVal TAS As String,  _
                    ByVal authenticationGuid As String,  _
                    ByVal searchWidth As String,  _
                    ByVal minimumScore As String,  _
                    ByVal callback As System.AsyncCallback,  _
                    ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ABRSearchByNameAdvancedSimpleProtocol", New Object() {name, postcode, legalName, tradingName, NSW, SA, ACT, VIC, WA, NT, QLD, TAS, authenticationGuid, searchWidth, minimumScore}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndABRSearchByNameAdvancedSimpleProtocol(ByVal asyncResult As System.IAsyncResult) As Payload
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abr.business.gov.au/ABRXMLSearch/ABRSearchByNameAdvancedSimpleProtocol2006"& _ 
"", RequestNamespace:="http://abr.business.gov.au/ABRXMLSearch/", ResponseNamespace:="http://abr.business.gov.au/ABRXMLSearch/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ABRSearchByNameAdvancedSimpleProtocol2006( _
                    ByVal name As String,  _
                    ByVal postcode As String,  _
                    ByVal legalName As String,  _
                    ByVal tradingName As String,  _
                    ByVal NSW As String,  _
                    ByVal SA As String,  _
                    ByVal ACT As String,  _
                    ByVal VIC As String,  _
                    ByVal WA As String,  _
                    ByVal NT As String,  _
                    ByVal QLD As String,  _
                    ByVal TAS As String,  _
                    ByVal authenticationGuid As String,  _
                    ByVal searchWidth As String,  _
                    ByVal minimumScore As String,  _
                    ByVal maxSearchResults As String) As <System.Xml.Serialization.XmlElementAttribute("ABRPayloadSearchResults", IsNullable:=true)> Payload
            Dim results() As Object = Me.Invoke("ABRSearchByNameAdvancedSimpleProtocol2006", New Object() {name, postcode, legalName, tradingName, NSW, SA, ACT, VIC, WA, NT, QLD, TAS, authenticationGuid, searchWidth, minimumScore, maxSearchResults})
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        Public Function BeginABRSearchByNameAdvancedSimpleProtocol2006( _
                    ByVal name As String,  _
                    ByVal postcode As String,  _
                    ByVal legalName As String,  _
                    ByVal tradingName As String,  _
                    ByVal NSW As String,  _
                    ByVal SA As String,  _
                    ByVal ACT As String,  _
                    ByVal VIC As String,  _
                    ByVal WA As String,  _
                    ByVal NT As String,  _
                    ByVal QLD As String,  _
                    ByVal TAS As String,  _
                    ByVal authenticationGuid As String,  _
                    ByVal searchWidth As String,  _
                    ByVal minimumScore As String,  _
                    ByVal maxSearchResults As String,  _
                    ByVal callback As System.AsyncCallback,  _
                    ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ABRSearchByNameAdvancedSimpleProtocol2006", New Object() {name, postcode, legalName, tradingName, NSW, SA, ACT, VIC, WA, NT, QLD, TAS, authenticationGuid, searchWidth, minimumScore, maxSearchResults}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndABRSearchByNameAdvancedSimpleProtocol2006(ByVal asyncResult As System.IAsyncResult) As Payload
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abr.business.gov.au/ABRXMLSearch/SearchByABNv200506", RequestNamespace:="http://abr.business.gov.au/ABRXMLSearch/", ResponseNamespace:="http://abr.business.gov.au/ABRXMLSearch/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SearchByABNv200506(ByVal searchString As String, ByVal includeHistoricalDetails As String, ByVal authenticationGuid As String) As <System.Xml.Serialization.XmlElementAttribute("ABRPayloadSearchResults", IsNullable:=true)> Payload
            Dim results() As Object = Me.Invoke("SearchByABNv200506", New Object() {searchString, includeHistoricalDetails, authenticationGuid})
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        Public Function BeginSearchByABNv200506(ByVal searchString As String, ByVal includeHistoricalDetails As String, ByVal authenticationGuid As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SearchByABNv200506", New Object() {searchString, includeHistoricalDetails, authenticationGuid}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSearchByABNv200506(ByVal asyncResult As System.IAsyncResult) As Payload
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abr.business.gov.au/ABRXMLSearch/SearchByASICv200506", RequestNamespace:="http://abr.business.gov.au/ABRXMLSearch/", ResponseNamespace:="http://abr.business.gov.au/ABRXMLSearch/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SearchByASICv200506(ByVal searchString As String, ByVal includeHistoricalDetails As String, ByVal authenticationGuid As String) As <System.Xml.Serialization.XmlElementAttribute("ABRPayloadSearchResults", IsNullable:=true)> Payload
            Dim results() As Object = Me.Invoke("SearchByASICv200506", New Object() {searchString, includeHistoricalDetails, authenticationGuid})
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        Public Function BeginSearchByASICv200506(ByVal searchString As String, ByVal includeHistoricalDetails As String, ByVal authenticationGuid As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SearchByASICv200506", New Object() {searchString, includeHistoricalDetails, authenticationGuid}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSearchByASICv200506(ByVal asyncResult As System.IAsyncResult) As Payload
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abr.business.gov.au/ABRXMLSearch/SearchByPostcode", RequestNamespace:="http://abr.business.gov.au/ABRXMLSearch/", ResponseNamespace:="http://abr.business.gov.au/ABRXMLSearch/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SearchByPostcode(ByVal postcode As String, ByVal authenticationGuid As String) As <System.Xml.Serialization.XmlElementAttribute("ABRPayloadSearchResults", IsNullable:=true)> Payload
            Dim results() As Object = Me.Invoke("SearchByPostcode", New Object() {postcode, authenticationGuid})
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        Public Function BeginSearchByPostcode(ByVal postcode As String, ByVal authenticationGuid As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SearchByPostcode", New Object() {postcode, authenticationGuid}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSearchByPostcode(ByVal asyncResult As System.IAsyncResult) As Payload
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abr.business.gov.au/ABRXMLSearch/SearchByABNStatus", RequestNamespace:="http://abr.business.gov.au/ABRXMLSearch/", ResponseNamespace:="http://abr.business.gov.au/ABRXMLSearch/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SearchByABNStatus(ByVal postcode As String, ByVal activeABNsOnly As String, ByVal currentGSTRegistrationOnly As String, ByVal entityTypeCode As String, ByVal authenticationGuid As String) As <System.Xml.Serialization.XmlElementAttribute("ABRPayloadSearchResults", IsNullable:=true)> Payload
            Dim results() As Object = Me.Invoke("SearchByABNStatus", New Object() {postcode, activeABNsOnly, currentGSTRegistrationOnly, entityTypeCode, authenticationGuid})
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        Public Function BeginSearchByABNStatus(ByVal postcode As String, ByVal activeABNsOnly As String, ByVal currentGSTRegistrationOnly As String, ByVal entityTypeCode As String, ByVal authenticationGuid As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SearchByABNStatus", New Object() {postcode, activeABNsOnly, currentGSTRegistrationOnly, entityTypeCode, authenticationGuid}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSearchByABNStatus(ByVal asyncResult As System.IAsyncResult) As Payload
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abr.business.gov.au/ABRXMLSearch/SearchByRegistrationEvent", RequestNamespace:="http://abr.business.gov.au/ABRXMLSearch/", ResponseNamespace:="http://abr.business.gov.au/ABRXMLSearch/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SearchByRegistrationEvent(ByVal postcode As String, ByVal state As String, ByVal entityTypeCode As String, ByVal month As String, ByVal year As String, ByVal authenticationGuid As String) As <System.Xml.Serialization.XmlElementAttribute("ABRPayloadSearchResults", IsNullable:=true)> Payload
            Dim results() As Object = Me.Invoke("SearchByRegistrationEvent", New Object() {postcode, state, entityTypeCode, month, year, authenticationGuid})
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        Public Function BeginSearchByRegistrationEvent(ByVal postcode As String, ByVal state As String, ByVal entityTypeCode As String, ByVal month As String, ByVal year As String, ByVal authenticationGuid As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SearchByRegistrationEvent", New Object() {postcode, state, entityTypeCode, month, year, authenticationGuid}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSearchByRegistrationEvent(ByVal asyncResult As System.IAsyncResult) As Payload
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abr.business.gov.au/ABRXMLSearch/SearchByUpdateEvent", RequestNamespace:="http://abr.business.gov.au/ABRXMLSearch/", ResponseNamespace:="http://abr.business.gov.au/ABRXMLSearch/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SearchByUpdateEvent(ByVal postcode As String, ByVal state As String, ByVal entityTypeCode As String, ByVal updatedate As String, ByVal authenticationGuid As String) As <System.Xml.Serialization.XmlElementAttribute("ABRPayloadSearchResults", IsNullable:=true)> Payload
            Dim results() As Object = Me.Invoke("SearchByUpdateEvent", New Object() {postcode, state, entityTypeCode, updatedate, authenticationGuid})
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        Public Function BeginSearchByUpdateEvent(ByVal postcode As String, ByVal state As String, ByVal entityTypeCode As String, ByVal updatedate As String, ByVal authenticationGuid As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SearchByUpdateEvent", New Object() {postcode, state, entityTypeCode, updatedate, authenticationGuid}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSearchByUpdateEvent(ByVal asyncResult As System.IAsyncResult) As Payload
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abr.business.gov.au/ABRXMLSearch/SearchByCharity", RequestNamespace:="http://abr.business.gov.au/ABRXMLSearch/", ResponseNamespace:="http://abr.business.gov.au/ABRXMLSearch/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SearchByCharity(ByVal postcode As String, ByVal state As String, ByVal charityTypeCode As String, ByVal concessionTypeCode As String, ByVal authenticationGuid As String) As <System.Xml.Serialization.XmlElementAttribute("ABRPayloadSearchResults", IsNullable:=true)> Payload
            Dim results() As Object = Me.Invoke("SearchByCharity", New Object() {postcode, state, charityTypeCode, concessionTypeCode, authenticationGuid})
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        Public Function BeginSearchByCharity(ByVal postcode As String, ByVal state As String, ByVal charityTypeCode As String, ByVal concessionTypeCode As String, ByVal authenticationGuid As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SearchByCharity", New Object() {postcode, state, charityTypeCode, concessionTypeCode, authenticationGuid}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSearchByCharity(ByVal asyncResult As System.IAsyncResult) As Payload
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://abr.business.gov.au/ABRXMLSearch/SearchByABNv200709", RequestNamespace:="http://abr.business.gov.au/ABRXMLSearch/", ResponseNamespace:="http://abr.business.gov.au/ABRXMLSearch/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SearchByABNv200709(ByVal searchString As String, ByVal includeHistoricalDetails As String, ByVal authenticationGuid As String) As <System.Xml.Serialization.XmlElementAttribute("ABRPayloadSearchResults", IsNullable:=true)> Payload
            Dim results() As Object = Me.Invoke("SearchByABNv200709", New Object() {searchString, includeHistoricalDetails, authenticationGuid})
            Return CType(results(0),Payload)
        End Function
        
        '<remarks/>
        Public Function BeginSearchByABNv200709(ByVal searchString As String, ByVal includeHistoricalDetails As String, ByVal authenticationGuid As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SearchByABNv200709", New Object() {searchString, includeHistoricalDetails, authenticationGuid}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSearchByABNv200709(ByVal asyncResult As System.IAsyncResult) As Payload
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Payload)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class Payload
        
        '<remarks/>
        Public request As ExternalRequest
        
        '<remarks/>
        Public response As Response
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ExternalRequestIdentifierSearch)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ExternalRequestNameSearch)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ExternalRequestNameSearchAdvanced)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ExternalRequestNameSearchAdvanced2006)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ExternalRequestABNFilter)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ExternalRequestABNEventFilter)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ExternalRequestABNStatusFilter)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ExternalRequestABNCharityFilter)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ExternalRequestABNUpdateEventFilter))>  _
    Public Class ExternalRequest
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("externalRequestABNCharityFilter", GetType(ExternalRequestABNCharityFilter)),  _
         System.Xml.Serialization.XmlElementAttribute("externalRequestABNUpdateEventFilter", GetType(ExternalRequestABNUpdateEventFilter)),  _
         System.Xml.Serialization.XmlElementAttribute("externalRequestABNFilter", GetType(ExternalRequestABNFilter)),  _
         System.Xml.Serialization.XmlElementAttribute("nameSearchRequestAdvanced2006", GetType(ExternalRequestNameSearchAdvanced2006)),  _
         System.Xml.Serialization.XmlElementAttribute("externalRequestABNEventFilter", GetType(ExternalRequestABNEventFilter)),  _
         System.Xml.Serialization.XmlElementAttribute("nameSearchRequest", GetType(ExternalRequestNameSearch)),  _
         System.Xml.Serialization.XmlElementAttribute("externalRequestABNStatusFilter", GetType(ExternalRequestABNStatusFilter)),  _
         System.Xml.Serialization.XmlElementAttribute("identifierSearchRequest", GetType(ExternalRequestIdentifierSearch)),  _
         System.Xml.Serialization.XmlElementAttribute("nameSearchRequestAdvanced", GetType(ExternalRequestNameSearchAdvanced))>  _
        Public Item As ExternalRequest
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class ExternalRequestABNCharityFilter
        Inherits ExternalRequestABNFilter
        
        '<remarks/>
        Public state As String
        
        '<remarks/>
        Public charityTypeCode As String
        
        '<remarks/>
        Public concessionTypeCode As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ExternalRequestABNEventFilter)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ExternalRequestABNStatusFilter)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ExternalRequestABNCharityFilter)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ExternalRequestABNUpdateEventFilter))>  _
    Public MustInherit Class ExternalRequestABNFilter
        Inherits ExternalRequest
        
        '<remarks/>
        Public authenticationGUID As String
        
        '<remarks/>
        Public postcode As String
        
        '<remarks/>
        Public entityTypeCode As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class ExternalRequestABNEventFilter
        Inherits ExternalRequestABNFilter
        
        '<remarks/>
        Public state As String
        
        '<remarks/>
        Public month As Integer
        
        '<remarks/>
        Public year As Integer
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class ExternalRequestABNStatusFilter
        Inherits ExternalRequestABNFilter
        
        '<remarks/>
        Public activeABNs As String
        
        '<remarks/>
        Public currentGSTRegistrationOnly As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class ExternalRequestABNUpdateEventFilter
        Inherits ExternalRequestABNFilter
        
        '<remarks/>
        Public state As String
        
        '<remarks/>
        Public updateDate As Date
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class ExternalRequestNameSearchAdvanced2006
        Inherits ExternalRequestNameSearchAdvanced
        
        '<remarks/>
        Public maxSearchResults As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ExternalRequestNameSearchAdvanced2006))>  _
    Public Class ExternalRequestNameSearchAdvanced
        Inherits ExternalRequestNameSearch
        
        '<remarks/>
        Public searchWidth As String
        
        '<remarks/>
        Public minimumScore As Integer
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ExternalRequestNameSearchAdvanced)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ExternalRequestNameSearchAdvanced2006))>  _
    Public Class ExternalRequestNameSearch
        Inherits ExternalRequest
        
        '<remarks/>
        Public authenticationGUID As String
        
        '<remarks/>
        Public name As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public filters As ExternalRequestFilters
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class ExternalRequestFilters
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public nameType As ExternalRequestFilterNameType
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public postcode As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public stateCode As ExternalRequestFilterStateCode
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class ExternalRequestFilterNameType
        
        '<remarks/>
        Public tradingName As String
        
        '<remarks/>
        Public legalName As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class CharityType
        
        '<remarks/>
        Public charityTypeDescription As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public effectiveFrom As Date
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public effectiveTo As Date
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class CharitableFund
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("pbiName")>  _
        Public pbiName() As OrganisationSimpleName
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public effectiveFrom As Date
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public effectiveTo As Date
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class OrganisationSimpleName
        Inherits Organisation
        
        '<remarks/>
        Public score As Integer
        
        '<remarks/>
        Public isCurrentIndicator As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(OrganisationName)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(OrganisationSimpleName))>  _
    Public Class Organisation
        
        '<remarks/>
        Public organisationName As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class OrganisationName
        Inherits Organisation
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public effectiveFrom As Date
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("effectiveToBlank", GetType(System.Object)),  _
         System.Xml.Serialization.XmlElementAttribute("effectiveTo", GetType(System.DateTime), DataType:="date")>  _
        Public Item As Object
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class SearchResultsRecord
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ABN")>  _
        Public ABN() As IdentifierSummary
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("legalName", GetType(IndividualSimpleName)),  _
         System.Xml.Serialization.XmlElementAttribute("dgrFundName", GetType(OrganisationSimpleName)),  _
         System.Xml.Serialization.XmlElementAttribute("PBIEName", GetType(OrganisationSimpleName)),  _
         System.Xml.Serialization.XmlElementAttribute("otherTradingName", GetType(OrganisationSimpleName)),  _
         System.Xml.Serialization.XmlElementAttribute("mainName", GetType(OrganisationSimpleName)),  _
         System.Xml.Serialization.XmlElementAttribute("mainTradingName", GetType(OrganisationSimpleName)),  _
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")>  _
        Public Items() As Object
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ItemsElementName"),  _
         System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public ItemsElementName() As ItemsChoiceType
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("mainBusinessPhysicalAddress", IsNullable:=true)>  _
        Public mainBusinessPhysicalAddress() As AddressSimple
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class IdentifierSummary
        
        '<remarks/>
        Public identifierValue As String
        
        '<remarks/>
        Public identifierStatus As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class IndividualSimpleName
        Inherits Individual
        
        '<remarks/>
        Public score As Integer
        
        '<remarks/>
        Public isCurrentIndicator As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(IndividualName)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(IndividualSimpleName))>  _
    Public Class Individual
        
        '<remarks/>
        Public fullName As String
        
        '<remarks/>
        Public givenName As String
        
        '<remarks/>
        Public otherGivenName As String
        
        '<remarks/>
        Public familyName As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class IndividualName
        Inherits Individual
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public effectiveFrom As Date
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public effectiveTo As Date
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/", IncludeInSchema:=false)>  _
    Public Enum ItemsChoiceType
        
        '<remarks/>
        legalName
        
        '<remarks/>
        dgrFundName
        
        '<remarks/>
        PBIEName
        
        '<remarks/>
        otherTradingName
        
        '<remarks/>
        mainName
        
        '<remarks/>
        mainTradingName
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class AddressSimple
        Inherits Address
        
        '<remarks/>
        Public isCurrentIndicator As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(AddressDetails)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(AddressSimple)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(AddressFull))>  _
    Public MustInherit Class Address
        
        '<remarks/>
        Public stateCode As String
        
        '<remarks/>
        Public postcode As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class AddressDetails
        Inherits Address
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public effectiveFrom As Date
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public effectiveTo As Date
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class AddressFull
        Inherits Address
        
        '<remarks/>
        Public addressLine1 As String
        
        '<remarks/>
        Public addressLine2 As String
        
        '<remarks/>
        Public suburb As String
        
        '<remarks/>
        Public countryName As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class SuperannuationStatus
        
        '<remarks/>
        Public complyingCode As String
        
        '<remarks/>
        Public complyingDescription As String
        
        '<remarks/>
        Public regulator As String
        
        '<remarks/>
        Public exceptionMessage As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class DgrFund
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("dgrFundName")>  _
        Public dgrFundName() As OrganisationSimpleName
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public endorsedFrom As Date
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public endorsedTo As Date
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class CharityConcession
        
        '<remarks/>
        Public endorsementType As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public effectiveFrom As Date
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public effectiveTo As Date
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class DGREndorsement
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public endorsedFrom As Date
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public endorsedTo As Date
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class GoodsAndServicesTax
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public effectiveFrom As Date
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public effectiveTo As Date
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class EntityType
        
        '<remarks/>
        Public entityTypeCode As String
        
        '<remarks/>
        Public entityDescription As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class EntityStatus
        
        '<remarks/>
        Public entityStatusCode As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public effectiveFrom As Date
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public effectiveTo As Date
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class Identifier
        
        '<remarks/>
        Public identifierValue As String
        
        '<remarks/>
        Public isCurrentIndicator As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public replacedIdentifierValue As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public replacedFrom As Date
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ResponseABNList)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ResponseSearchResultsList)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ResponseBusinessEntity)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ResponseBusinessEntity200506)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ResponseBusinessEntity200709)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ResponseException))>  _
    Public Class ResponseBody
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class ResponseABNList
        Inherits ResponseBody
        
        '<remarks/>
        Public numberOfRecords As Integer
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("abn")>  _
        Public abn() As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class ResponseSearchResultsList
        Inherits ResponseBody
        
        '<remarks/>
        Public numberOfRecords As Integer
        
        '<remarks/>
        Public exceedsMaximum As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("searchResultsRecord")>  _
        Public searchResultsRecord() As SearchResultsRecord
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ResponseBusinessEntity200506)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ResponseBusinessEntity200709))>  _
    Public Class ResponseBusinessEntity
        Inherits ResponseBody
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public recordLastUpdatedDate As Date
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ABN")>  _
        Public ABN() As Identifier
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("entityStatus")>  _
        Public entityStatus() As EntityStatus
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public ASICNumber As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public entityType As EntityType
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("goodsAndServicesTax", IsNullable:=true)>  _
        Public goodsAndServicesTax() As GoodsAndServicesTax
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("dgrEndorsement", IsNullable:=true)>  _
        Public dgrEndorsement() As DGREndorsement
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("legalName", GetType(IndividualName)),  _
         System.Xml.Serialization.XmlElementAttribute("mainName", GetType(OrganisationName))>  _
        Public Items() As Object
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("mainTradingName", IsNullable:=true)>  _
        Public mainTradingName() As OrganisationName
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("otherTradingName", IsNullable:=true)>  _
        Public otherTradingName() As OrganisationName
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("mainBusinessPhysicalAddress", IsNullable:=true)>  _
        Public mainBusinessPhysicalAddress() As AddressDetails
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("dgrFund", IsNullable:=true)>  _
        Public dgrFund() As DgrFund
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ResponseBusinessEntity200709))>  _
    Public Class ResponseBusinessEntity200506
        Inherits ResponseBusinessEntity
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("charityType", IsNullable:=true)>  _
        Public charityType() As CharityType
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("taxConcessionCharityEndorsement", IsNullable:=true)>  _
        Public taxConcessionCharityEndorsement() As CharityConcession
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("publicBenevolentInstitutionEmployer", IsNullable:=true)>  _
        Public publicBenevolentInstitutionEmployer() As CharitableFund
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class ResponseBusinessEntity200709
        Inherits ResponseBusinessEntity200506
        
        '<remarks/>
        Public superannuationStatus As SuperannuationStatus
        
        '<remarks/>
        Public mainPostalPhysicalAddress As AddressFull
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class ResponseException
        Inherits ResponseBody
        
        '<remarks/>
        Public exceptionDescription As String
        
        '<remarks/>
        Public exceptionCode As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class Response
        
        '<remarks/>
        Public usageStatement As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public dateRegisterLastUpdated As Date
        
        '<remarks/>
        Public dateTimeRetrieved As Date
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("businessEntity200506", GetType(ResponseBusinessEntity200506)),  _
         System.Xml.Serialization.XmlElementAttribute("searchResultsList", GetType(ResponseSearchResultsList)),  _
         System.Xml.Serialization.XmlElementAttribute("abnList", GetType(ResponseABNList)),  _
         System.Xml.Serialization.XmlElementAttribute("businessEntity", GetType(ResponseBusinessEntity)),  _
         System.Xml.Serialization.XmlElementAttribute("exception", GetType(ResponseException)),  _
         System.Xml.Serialization.XmlElementAttribute("businessEntity200709", GetType(ResponseBusinessEntity200709))>  _
        Public Item As ResponseBody
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class ExternalRequestFilterStateCode
        
        '<remarks/>
        Public QLD As String
        
        '<remarks/>
        Public NT As String
        
        '<remarks/>
        Public SA As String
        
        '<remarks/>
        Public WA As String
        
        '<remarks/>
        Public VIC As String
        
        '<remarks/>
        Public ACT As String
        
        '<remarks/>
        Public TAS As String
        
        '<remarks/>
        Public NSW As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://abr.business.gov.au/ABRXMLSearch/")>  _
    Public Class ExternalRequestIdentifierSearch
        Inherits ExternalRequest
        
        '<remarks/>
        Public authenticationGUID As String
        
        '<remarks/>
        Public identifierType As String
        
        '<remarks/>
        Public identifierValue As String
        
        '<remarks/>
        Public history As String
    End Class
End Namespace
